[profile.default]
src     = "src"
out     = "out"
libs    = ["lib"]
test    = "test"
script  = "script"

solc_version   = "0.8.33"
optimizer      = true
optimizer_runs = 200
via_ir         = true

fuzz.runs      = 256
verbosity      = 2

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@chainlink/contracts-ccip/contracts/=lib/chainlink-ccip/chains/evm/contracts/",
    "@chainlink/contracts/=lib/chainlink-evm/contracts/",
    "@chainlink/local/=lib/chainlink-local/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

[rpc_endpoints]
sepolia     = "${ETHEREUM_SEPOLIA_RPC_URL}"
amoy        = "${POLYGON_AMOY_RPC_URL}"
anvil       = "http://localhost:8545"

[etherscan]
sepolia     = { key = "${ETHERSCAN_API_KEY}", chain = "sepolia" }

[profile.ci]
fuzz.runs = 1000
verbosity = 3

[profile.lite]
optimizer_runs = 1
